---

- name: Deploy Apidocs
  hosts: apidocs
  user: ubuntu
  sudo: True

  vars:
    git_user: pp
    git_pass: 1qaz1qaz
    app_name: apidocs
    repo_url: "https://{{ git_user }}:{{ git_pass }}@phab.octo.ai/diffusion/APIDOC/apidocs.git"
    repo_remote: origin
    repo_version: master
    repo_dir_name: "{{ ansible_date_time.epoch }}"
    apps_dir: /home/ubuntu/apps
    host_name: developers.octo.ai

  tasks:
    - name: Ensuring app dir is present
      action: file dest={{ apps_dir }}/{{ app_name }} state=directory

    - name: Ensure directory for apidocs
      action: file dest={{apps_dir}}/{{app_name}}/src state=directory

    - name: deploy code from repository
      git: repo={{ repo_url }}
        dest={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}
        remote={{ repo_remote }}
        version={{ repo_version }}
        accept_hostkey=yes
        force=True
      async: 30
      poll: 30

    - name: Performing build operation
      shell: cd {{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/ && ./build.sh

    - name: Symlinking deployment to run directory
      file: src={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/site/ dest={{ apps_dir }}/{{ app_name }}/run state=link force=yes

    - name: Copying nginx script
      copy: src=../templates/nginx/{{ host_name }} dest=/etc/nginx/sites-enabled/{{ host_name }}

    - name: Restarting nginx
      shell: sudo service nginx restart