---

- name: Deploy Recurring Jobs
  hosts: redis
  user: ubuntu
  sudo: True

  vars:
    git_user: pp
    git_pass: 1qaz1qaz
    app_name: recurring_jobs
    scheduler_name: resque_scheduler
    worker_name: resque_worker
    repo_url: "https://{{ git_user }}:{{ git_pass }}@phab.octo.ai/diffusion/RECURR/recurring-jobs.git"
    repo_remote: origin
    repo_version: master
    repo_dir_name: "{{ ansible_date_time.epoch }}"
    apps_dir: /home/ubuntu/apps

  tasks:
    - name: Ensuring app dir is present
      action: file dest={{ apps_dir }}/{{ app_name }} state=directory
      tags:
        - deploy

    - name: Ensure directory for api_handler
      action: file dest={{apps_dir}}/{{app_name}}/src state=directory
      tags:
        - deploy

    - name: deploy code from repository
      git: repo={{ repo_url }}
        dest={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}
        remote={{ repo_remote }}
        version={{ repo_version }}
        accept_hostkey=yes
        force=True
      async: 30
      poll: 30
      tags:
        - deploy

    - name: Symlink gems and config
      file: src={{ apps_dir }}/config/ dest={{ apps_dir }}/gems/octo-core/lib/octocore/config/config state=link force=yes
      tags:
        - deploy

    - name: Symlink Recurring Jobs and config
      file: src={{ apps_dir }}/config/ dest={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/lib/config/config state=link force=yes
      tags:
        - deploy

    - name: Performing bundle install
      shell: cd {{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/ && bundle install
      tags:
        - deploy

    - name: Making sure GOD is started
      shell: cd {{ apps_dir }}/heaven/run/ && bundle exec god -c octo.god
      tags:
        - restart
        - deploy

    - name: Copying resque_scheduler GOD script
      copy: src=../god/{{ scheduler_name }}.god dest={{ apps_dir }}/heaven/run/lib/{{ scheduler_name }}.god
      tags:
        - restart
        - deploy

    - name: Copying resque_worker GOD script
      copy: src=../god/{{ worker_name }}.god dest={{ apps_dir }}/heaven/run/lib/{{ worker_name }}.god
      tags:
        - restart
        - deploy


    - name: Stopping Resque Scheduler
      shell: cd {{ apps_dir }}/heaven/run/ && bundle exec god load octo.god && bundle exec god stop {{ scheduler_name }}
      ignore_errors: True
      tags:
        - deploy
        - restart

    - name: Stopping Resque Worker
      shell: cd {{ apps_dir }}/heaven/run/ && bundle exec god stop {{ worker_name }}
      ignore_errors: True
      tags:
        - deploy
        - restart

    - name: Symlinking deployment to run directory
      file: src={{ apps_dir }}/{{ app_name }}/src/{{ repo_dir_name }}/ dest={{ apps_dir }}/{{ app_name }}/run state=link force=yes
      tags:
        - deploy

    - name: Starting Resque Scheduler
      shell: cd {{ apps_dir }}/heaven/run/ && bundle exec god load octo.god && bundle exec god start {{ scheduler_name }}
      tags:
        - deploy
        - restart

    - name: Starting Resque Workers
      shell: cd {{ apps_dir }}/heaven/run/ && bundle exec god start {{ worker_name }}
      tags:
        - deploy
        - restart

    - name: Cleaning old sources files
      shell: cd {{ apps_dir }}/{{ app_name }}/src/ && (ls -t|head -n 5;ls)| sort| uniq -u|xargs rm -rf
      tags:
        - deploy
        - restart

